### ISSUE TITLE
Create the demo scene

### ISSUE THREAD

**Issue by Jazy5552** [cap4053-cheeky-pixels/Embody#38]
We should create a fresh and new demo scene, showcasing all of our work. Below are some notes I took of priorities and pending fixes after talking with Alek. I will try fix most of them in the next couple hours, afterwards Alek will help out as well. If anyone else wants to help or finds other issues that need fixes feel free to mention it.

Top Priorities
- Rooms with enemies
- Shooting with player
- Possession

- [x] Stop enemy from shooting when dead
- [x] Fix the room collider so it detects the player
- [x] Update enemy with default stats (Remove my movement script)
- [x] Update player stats
- [x] Move enemy shooting logic into Enemy.cs (Out of EnemyWeaponController)
- [x] Change enemy movement to simplemove
- [x] Tag walls
- [x] Make projectiles destroy on hit (ANY HIT)
- [x] Possession
- [x] Fix player shooting (Change to weapon controller fire)

**Comment by Jazy5552** [comment]
Few things left
- [ ] Fill the rest of the rooms with enemies
- [ ] Maybe add some walls within the rooms as obstacles
- [ ] Add varied enemies

**Comment by AleksandrHovhannisyan** [comment]
Sounds good :) The second one may be tricky with enemies pursuing the player; we could use navmeshes and give each enemy an agent so they navigate around walls. But idk if we should. What do you think?

**Comment by Jazy5552** [comment]
Na, that sounds too complicated. I was thinking like a little wall so they would run into it like the dumb AI they are lol. But it's fine without it.
